### ISSUE TITLE
Contribute to pymrt

### ISSUE THREAD

**Issue by cfhammill** [neuropoly/mp2rage#3]
Hi all thanks for the useful code.

I was wondering if this be contributed to pymrt, to avoid having to modify an installed package. Pymrt is developed on bitbucket, and it seems like it wouldn't be too hard to set up a pull request.

Happy to assist with the process if this is of interest to you.

**Comment by jcohenadad** [comment]
@cfhammill thanks a lot for your inputs-- we are working on another implementation in a wider and more active project: https://github.com/qMRLab/qMRLab/issues/255

so, once the implementation in qmrlab is completed, we will likely redirect this repository to qmrlab.

**Comment by cfhammill** [comment]
Great, thank you @jcohenadad!
