### ISSUE TITLE
error when running the program

### ISSUE THREAD

**Issue by steamerja** [neuropoly/mp2rage#5]
Help is needed - I get the following error when I run the program.

Any guidance is greatly appreciated.

Jeff

mp2rage_compute_t1_map.py -i qa40021a_mp1_22_4500_1550-4100_uni.nii.g -acqparam ti=1550,4100:alpha=6,6:tr_seq=4500:tr_gre=4.8:matrix_sizes=240,240,160:bandwidths=370,370:part_fourier_factors=1.0,6/8,1.0:grappa_refs=0,24,0:grappa_factors=1,2,1 -t1range 100,3000 -o T1map.nii.gz,RHOmap.nii.gz
Traceback (most recent call last):
  File "/opt/bin/mp2rage_compute_t1_map.py", line 16, in <module>
    from parser import Parser, printv
  File "/opt/bin/parser.py", line 570
    print self.generate()
          ^
SyntaxError: invalid syntax

**Comment by mathieuboudreau** [comment]
It appears the code is written for Python 2 but you're using Python 3.

See README for installation instructions: https://github.com/neuropoly/mp2rage/blob/master/README.md

**Comment by steamerja** [comment]
Correct - I did confirm that - I did install adaconda3, which includes python ver 3.8.

However, the link noted in your "Step 1” is broken - is there an alternative site, which will allow me to set the appropriate environments for anaconda?

Jeff


On Aug 7, 2020, 5:58 PM -0400, Mathieu Boudreau <notifications@github.com>, wrote:

It appears the code is written for Python 2 but you're using Python 3.

See README for installation instructions: https://github.com/neuropoly/mp2rage/blob/master/README.md

**Comment by jcohenadad** [comment]
Hi Jeff,

I've updated the link under Step 1. 

Also please note that this repository is no more maintained (I've now added a disclaimer)-- we encourage you to download [qMRLab](https://qmrlab.readthedocs.io/en/master/mp2rage_batch.html?highlight=mp2rage) instead, which also has a module to compute T1maps from MP2RAGE data.

**Comment by steamerja** [comment]
I appreciate your help and would like to continue to make it work.

I now have python ver 2.7 setup but still get an error - see attachment.

The pymrt package is installed in /usr
On Aug 8, 2020, 11:09 AM -0400, Julien Cohen-Adad <notifications@github.com>, wrote:

Hi Jeff,

I've updated the link under Step 1.

Also please note that this repository is no more maintained (I've now added a disclaimer)-- we encourage you to download qMRLab<https://qmrlab.readthedocs.io/en/master/mp2rage_batch.html?highlight=mp2rage> instead, which also has a module to compute T1maps from MP2RAGE data.

**Comment by steamerja** [comment]
Forgot to complete the message — Jeff

I appreciate your help and would like to continue to make it work.

I now have python ver 2.7 setup but still get an error - see attachment.

The pymrt package is installed in /usr/local/lib/python2.7/site-packages/pymrt

Any suggestions?

Jeff

On Aug 9, 2020, 11:06 AM -0400, Jeffrey A. Stanley, Ph.D. <av6252@wayne.edu>, wrote:
I appreciate your help and would like to continue to make it work.

I now have python ver 2.7 setup but still get an error - see attachment.

The pymrt package is installed in /usr
On Aug 8, 2020, 11:09 AM -0400, Julien Cohen-Adad <notifications@github.com>, wrote:

Hi Jeff,

I've updated the link under Step 1.

Also please note that this repository is no more maintained (I've now added a disclaimer)-- we encourage you to download qMRLab<https://qmrlab.readthedocs.io/en/master/mp2rage_batch.html?highlight=mp2rage> instead, which also has a module to compute T1maps from MP2RAGE data.

**Comment by jcohenadad** [comment]
> I now have python ver 2.7 setup but still get an error - see attachment.

there is no attachment-- Please, do not answer via your email software, but rather on github directly
